# Generated by Django 3.2.7 on 2021-09-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_batch_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Course',
            new_name='course',
        ),
    ]
